title: nicanor.github.io
description: "Mis opiniones y experiencias como programador web"
author: "Nicanor Perera"
author_description: "Un flaco que juega a programar."
exclude: [README.md, LICENSE.md, Gemfile, Gemfile.lock]
plugins: ["jekyll-feed"]

url: https://nicanor.github.io

permalink: /:categories/:year/:month/:title/

email: nicanor@hey.com
github_username: nicanor
twitter_username: nicanorperera
linkedin_username: nicanor-perera
hey_username: nicanor

source_url: "https://github.com/nicanor/nicanor.github.io/blob/master/"

license: "CC-by"
license_url: https://creativecommons.org/licenses/by/4.0/
